version: '3.8'

services:

  drupal:
    image: drupal:latest
    ports: 
      - 8081:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:    
